# Generated by Django 5.2.5 on 2025-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
